- name: Save output to register variable
  hosts: ec2
  become: true
  tasks:
    - name: Installed nginx
      yum:
        name: nginx
        state: present
      register: nginx_installed_output
    
    - name: print the installed nginx output
      debug:
        var: nginx_installed_output

    - name: copy the output to remote file
      copy:
        content: "{{ nginx_installed_output }}"
        dest: /tmp/register_variable.txt