
## playbook to run roles
---
name: Deploy a mysql DB
hosts: db_server
roles:
  - python
  - mysql_db

## run roles with varible
---
name: Deploy a Web Server
hosts: web_server
roles:
  - role: mysql
    become: yes
    vars:
      mysql_user_name: dbadmin

  