---
- name: Lineinfile module
  hosts: all
  become: true
  tasks: 
    - name: Allow password authentication
      ansible.builtin.lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: PasswordAuthentication yes
        validate: 'sshd -t -f %s'
    - name: Add block og line
      ansible.builtin.blockinfile:
        state: present
        dest: /tmp/raghib.txt
        content: |
          you are doing great 
          Keep it up !!!
---
- name: reboot module demo
  hosts: ec2_host
  become: true
  tasks:
    - name: reboot hosts
      reboot:
        msg: "reboot ec2 instance"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: "whoami"
---
- hosts: ec2_host
  vars:
    repo: git@github.com:raghib1992/ansible.git
    dest: ~/ansible-repo
    file: ~/.ssh/id_rsa
  tasks:
  - name: Clone the Git repo
    git:
      repo: "{{ repo }}"
      dest: "{{ dest }}"
      version: master
      key_file: "{{ file  }}"
      update: yes