-
  name: Deploy a mysql DB
  hosts: db_server
  roles:
    - python
    - mysql_db

-
  name: Deploy a Web Server
  hosts: web_server
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
  command: /opt/monitor_webapp.py
  async: 360    #how long to run
  poll: 0       #how frequently check, by default 10sec, here 0 sec used, result will store into variable webapp_result
  register: webapp_result

-
  name: Monitor Database for 6 Minutes
  hosts: db_server
  command: /opt/monitor_database.py
  async: 360
  poll: 0
  register: database_result

-
  name: check the status of the tasks
  async_status: jid={{ webapp_result.ansible_job_id }}
  register: job_id
  until: job_result.finished
  retries: 30